version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: knowledge_db
    volumes:
      - ./data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
